[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "depth-keys" 
version = "0.1.0"
description = "Depth rig experiment processing pipeline"
requires-python = ">=3.12"

# The Core Dependencies
dependencies = [
    "scikit-learn",
    "numba",
    "scikit-image",
    "toml",
    "click",
    
    # Specific versions you requested
    #"sleap-io==0.5.7", # installed with sleap-nn
    "sleap-nn==0.2.0",
    "markolab-cli @ git+https://github.com/markolab/markolab-cli.git"
    # "markovids @ git+https://github.com/triesenmy3/markovids.git" # incorrect
    # "markovids @ git+https://github.com/TiernonRR/markovids-tr.git@tr_changes
    "markovids @ git+https://github.com/markolab/markovids.git@integrate_tr_changes"
]

# Optional: Tools for development (install via `pip install .[dev]`)
[project.optional-dependencies]
dev = [
    "ipykernel"
]

[project.scripts]
depth-keys = "depth_keys.cli:cli"

#[tool.setuptools.packages.find]
#where = ["src"]
#include = ["depth_keys*"]
#exclude = ["notebooks*", "models*", "example_scripts*"]
